In [6]:
x = [1, 2, 3]
y = [9, 7, 5]

x + y

## Perform x[i] + y[i] for all i in x, where len(x) == len(y)

def add_numbers_in_two_lists(x, y):
    if(len(x) != len(y)):
        raise ValueError("Expect len(x) == len(y)")
    n = len(x)
    out = []
    # out = [None]*n
    for i in range(n):
        out.append(x[i] + y[i])
    return out

In [5]:
add_numbers_in_two_lists(x, y)

[10, 9, 8]

In [9]:
import numpy as np

In [11]:
xn = np.array([1,2,3])
yn = np.array(y)

xn + yn

array([10,  9,  8])

In [12]:
np.random.seed(1)

In [17]:
np.random.randint(100)

72

In [19]:
x = np.zeros([3, 5, 7])
x.ndim

3

In [20]:
x

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [21]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
x.shape

(3, 5, 7)

In [25]:
np.array([1, 2, 3]) + 2

array([3, 4, 5])

Using with keyword to open a file

In [37]:
prices = [7, 1, 5, 3, 6, 4]
max = 0
buy_sell = (,)
dict = {}

In [44]:
for i in range(len(prices)):
    for j in range(i+1, len(prices)):
        value = prices[j] - prices[i]
        if value > max:
            max = 0
            buy_sell = [prices[i], prices[j]]

TypeError: '>' not supported between instances of 'int' and 'builtin_function_or_method'